# Generated by Django 2.0.5 on 2018-05-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('conference', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stadium_year_construction', models.IntegerField()),
                ('stadium_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('zip_code', models.IntegerField(max_length=9)),
                ('state', models.CharField(max_length=2)),
                ('total_students', models.IntegerField()),
                ('white_students', models.IntegerField()),
                ('black_students', models.IntegerField()),
                ('hispanic_students', models.IntegerField()),
                ('asian_students', models.IntegerField()),
                ('american_indian_students', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField()),
                ('scholarship_offer', models.BooleanField()),
                ('active', models.BooleanField()),
                ('college_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestbook.College')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('prefix', models.CharField(max_length=5)),
                ('suffix', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=10)),
                ('secondary_position', models.CharField(max_length=10)),
                ('forty_dash', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('twitter_handle', models.CharField(max_length=40)),
                ('recruit_year', models.IntegerField()),
                ('committed', models.BooleanField()),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestbook.HighSchool')),
            ],
        ),
    ]
